"""add_tags_to_research

Revision ID: 2cbc80c8543e
Revises: 40ad20cbfd6d
Create Date: 2026-03-11 15:07:46.739247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbc80c8543e'
down_revision: Union[str, None] = '40ad20cbfd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research', 'tags')
    # ### end Alembic commands ###
