"""add_user_notes_to_research

Revision ID: 40ad20cbfd6d
Revises: 1b10e0e3b8b9
Create Date: 2026-03-11 14:42:38.323309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ad20cbfd6d'
down_revision: Union[str, None] = '1b10e0e3b8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_messages_research_id_fkey', 'conversation_messages', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_messages', 'research', ['research_id'], ['id'])
    op.add_column('research', sa.Column('user_notes', sa.Text(), nullable=True))
    op.drop_constraint('research_findings_research_id_fkey', 'research_findings', type_='foreignkey')
    op.create_foreign_key(None, 'research_findings', 'research', ['research_id'], ['id'])
    op.drop_index('ix_research_notes_research_id', table_name='research_notes')
    op.create_index(op.f('ix_research_notes_id'), 'research_notes', ['id'], unique=False)
    op.drop_constraint('research_notes_research_id_fkey', 'research_notes', type_='foreignkey')
    op.create_foreign_key(None, 'research_notes', 'research', ['research_id'], ['id'])
    op.drop_constraint('research_sources_research_id_fkey', 'research_sources', type_='foreignkey')
    op.create_foreign_key(None, 'research_sources', 'research', ['research_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_sources', type_='foreignkey')
    op.create_foreign_key('research_sources_research_id_fkey', 'research_sources', 'research', ['research_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'research_notes', type_='foreignkey')
    op.create_foreign_key('research_notes_research_id_fkey', 'research_notes', 'research', ['research_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_research_notes_id'), table_name='research_notes')
    op.create_index('ix_research_notes_research_id', 'research_notes', ['research_id'], unique=False)
    op.drop_constraint(None, 'research_findings', type_='foreignkey')
    op.create_foreign_key('research_findings_research_id_fkey', 'research_findings', 'research', ['research_id'], ['id'], ondelete='CASCADE')
    op.drop_column('research', 'user_notes')
    op.drop_constraint(None, 'conversation_messages', type_='foreignkey')
    op.create_foreign_key('conversation_messages_research_id_fkey', 'conversation_messages', 'research', ['research_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
