"""Initial schema with conversation messages

Revision ID: 60e54212dad1
Revises:
Create Date: 2026-03-04 22:49:44.015279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e54212dad1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'research',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('query', sa.String(length=500), nullable=False),
        sa.Column('result', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('state_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_research_id'), 'research', ['id'], unique=False
    )
    op.create_table(
        'conversation_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('research_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('action_taken', sa.String(length=100), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_conversation_messages_id'),
        'conversation_messages',
        ['id'],
        unique=False
    )
    op.create_table(
        'research_sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('research_id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=2000), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=True),
        sa.Column('author', sa.String(length=200), nullable=True),
        sa.Column('content_snippet', sa.Text(), nullable=True),
        sa.Column('source_type', sa.String(length=50), nullable=True),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_research_sources_id'),
        'research_sources',
        ['id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_research_sources_id'), table_name='research_sources'
    )
    op.drop_table('research_sources')
    op.drop_index(
        op.f('ix_conversation_messages_id'),
        table_name='conversation_messages'
    )
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_research_id'), table_name='research')
    op.drop_table('research')
    # ### end Alembic commands ###
